<?php
/**
 * AvailableServiceResponsesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AvailableServiceResponsesTest Class Doc Comment
 *
 * @category    Class */
// * @description 可用物流服务
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AvailableServiceResponsesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AvailableServiceResponses"
     */
    public function testAvailableServiceResponses()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "estimate_cost"
     */
    public function testPropertyEstimateCost()
    {
    }

    /**
     * Test attribute "service_id"
     */
    public function testPropertyServiceId()
    {
    }

    /**
     * Test attribute "service_name_en"
     */
    public function testPropertyServiceNameEn()
    {
    }

    /**
     * Test attribute "service_name_zh"
     */
    public function testPropertyServiceNameZh()
    {
    }
}
