<?php
/**
 * DropoffSiteInfoResponsesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DropoffSiteInfoResponsesTest Class Doc Comment
 *
 * @category    Class */
// * @description ç©æµæå¡åé¡µä¿¡æ¯
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DropoffSiteInfoResponsesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DropoffSiteInfoResponses"
     */
    public function testDropoffSiteInfoResponses()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "district"
     */
    public function testPropertyDistrict()
    {
    }

    /**
     * Test attribute "dropoff_site_id"
     */
    public function testPropertyDropoffSiteId()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "province"
     */
    public function testPropertyProvince()
    {
    }

    /**
     * Test attribute "street1"
     */
    public function testPropertyStreet1()
    {
    }

    /**
     * Test attribute "street2"
     */
    public function testPropertyStreet2()
    {
    }

    /**
     * Test attribute "street3"
     */
    public function testPropertyStreet3()
    {
    }
}
