<?php
/**
 * ItemResponsesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ItemResponsesTest Class Doc Comment
 *
 * @category    Class */
// * @description 货品列表，至少一个
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemResponsesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemResponses"
     */
    public function testItemResponses()
    {
    }

    /**
     * Test attribute "buyer_id"
     */
    public function testPropertyBuyerId()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "item_title"
     */
    public function testPropertyItemTitle()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "order_line_item"
     */
    public function testPropertyOrderLineItem()
    {
    }

    /**
     * Test attribute "pay_pal_email"
     */
    public function testPropertyPayPalEmail()
    {
    }

    /**
     * Test attribute "pay_pal_message"
     */
    public function testPropertyPayPalMessage()
    {
    }

    /**
     * Test attribute "payment_date"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "posted_qty"
     */
    public function testPropertyPostedQty()
    {
    }

    /**
     * Test attribute "received_amount"
     */
    public function testPropertyReceivedAmount()
    {
    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "sold_date"
     */
    public function testPropertySoldDate()
    {
    }

    /**
     * Test attribute "sold_price"
     */
    public function testPropertySoldPrice()
    {
    }

    /**
     * Test attribute "sold_qty"
     */
    public function testPropertySoldQty()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }
}
