<?php
/**
 * ServiceInfoResponsesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServiceInfoResponsesTest Class Doc Comment
 *
 * @category    Class */
// * @description 物流服务
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceInfoResponsesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServiceInfoResponses"
     */
    public function testServiceInfoResponses()
    {
    }

    /**
     * Test attribute "description_en"
     */
    public function testPropertyDescriptionEn()
    {
    }

    /**
     * Test attribute "description_zh"
     */
    public function testPropertyDescriptionZh()
    {
    }

    /**
     * Test attribute "directions"
     */
    public function testPropertyDirections()
    {
    }

    /**
     * Test attribute "fee_description"
     */
    public function testPropertyFeeDescription()
    {
    }

    /**
     * Test attribute "incoterms"
     */
    public function testPropertyIncoterms()
    {
    }

    /**
     * Test attribute "is_support_elec"
     */
    public function testPropertyIsSupportElec()
    {
    }

    /**
     * Test attribute "max_length"
     */
    public function testPropertyMaxLength()
    {
    }

    /**
     * Test attribute "max_total_length"
     */
    public function testPropertyMaxTotalLength()
    {
    }

    /**
     * Test attribute "max_weight"
     */
    public function testPropertyMaxWeight()
    {
    }

    /**
     * Test attribute "name_en"
     */
    public function testPropertyNameEn()
    {
    }

    /**
     * Test attribute "name_zh"
     */
    public function testPropertyNameZh()
    {
    }

    /**
     * Test attribute "picture"
     */
    public function testPropertyPicture()
    {
    }

    /**
     * Test attribute "prescription"
     */
    public function testPropertyPrescription()
    {
    }

    /**
     * Test attribute "service_id"
     */
    public function testPropertyServiceId()
    {
    }
}
