<?php
/**
 * UpdateConsignPreferenceRequestDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateConsignPreferenceRequestDataTest Class Doc Comment
 *
 * @category    Class */
// * @description 交运偏好
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateConsignPreferenceRequestDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateConsignPreferenceRequestData"
     */
    public function testUpdateConsignPreferenceRequestData()
    {
    }

    /**
     * Test attribute "consign_preference_id"
     */
    public function testPropertyConsignPreferenceId()
    {
    }

    /**
     * Test attribute "dropoff_site_id"
     */
    public function testPropertyDropoffSiteId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "pickup_address"
     */
    public function testPropertyPickupAddress()
    {
    }

    /**
     * Test attribute "pickup_time"
     */
    public function testPropertyPickupTime()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
