<?php
/**
 * OpenApiApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eBay国际物流平台商户接口
 *
 * eBay国际物流平台商户接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OpenApiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OpenApiApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addAddressPreference
     *
     * 新增地址信息.
     *
     */
    public function testAddAddressPreference()
    {
    }

    /**
     * Test case for addConsignPreference
     *
     * 新增交运偏好.
     *
     */
    public function testAddConsignPreference()
    {
    }

    /**
     * Test case for addPackage
     *
     * 指定物流服务上传包裹.
     *
     */
    public function testAddPackage()
    {
    }

    /**
     * Test case for addPackageWithoutService
     *
     * 无指定物流服务上传包裹.
     *
     */
    public function testAddPackageWithoutService()
    {
    }

    /**
     * Test case for assignService
     *
     * 指定包裹物流服务.
     *
     */
    public function testAssignService()
    {
    }

    /**
     * Test case for cancelPackages
     *
     * 取消包裹信息.
     *
     */
    public function testCancelPackages()
    {
    }

    /**
     * Test case for confirmPackages
     *
     * 确认并交运包裹信息.
     *
     */
    public function testConfirmPackages()
    {
    }

    /**
     * Test case for deletePackages
     *
     * 删除包裹信息.
     *
     */
    public function testDeletePackages()
    {
    }

    /**
     * Test case for fetchToken
     *
     * 登录认证.
     *
     */
    public function testFetchToken()
    {
    }

    /**
     * Test case for getActualCost
     *
     * 获取包裹实际运费.
     *
     */
    public function testGetActualCost()
    {
    }

    /**
     * Test case for getAddressPreferenceList
     *
     * 获取地址信息列表.
     *
     */
    public function testGetAddressPreferenceList()
    {
    }

    /**
     * Test case for getConsignPreferenceList
     *
     * 获取交运偏好列表.
     *
     */
    public function testGetConsignPreferenceList()
    {
    }

    /**
     * Test case for getDropoffSiteList
     *
     * 获取自送站点列表.
     *
     */
    public function testGetDropoffSiteList()
    {
    }

    /**
     * Test case for getHandoverSheet
     *
     * 获取交接单打印详情.
     *
     */
    public function testGetHandoverSheet()
    {
    }

    /**
     * Test case for getItemPackageId
     *
     * 查询物品包裹ID.
     *
     */
    public function testGetItemPackageId()
    {
    }

    /**
     * Test case for getLabel
     *
     * 获取面单打印详情.
     *
     */
    public function testGetLabel()
    {
    }

    /**
     * Test case for getPackageDetail
     *
     * 获取包裹详情.
     *
     */
    public function testGetPackageDetail()
    {
    }

    /**
     * Test case for getPackageStatus
     *
     * 获取包裹状态.
     *
     */
    public function testGetPackageStatus()
    {
    }

    /**
     * Test case for getServiceList
     *
     * 获取物流服务列表.
     *
     */
    public function testGetServiceList()
    {
    }

    /**
     * Test case for getTrackingDetail
     *
     * 获取包裹物流跟踪信息.
     *
     */
    public function testGetTrackingDetail()
    {
    }

    /**
     * Test case for recreatePackage
     *
     * 重新发货.
     *
     */
    public function testRecreatePackage()
    {
    }

    /**
     * Test case for updateAddressPreference
     *
     * 更新地址信息.
     *
     */
    public function testUpdateAddressPreference()
    {
    }

    /**
     * Test case for updateConsignPreference
     *
     * 更新交运偏好.
     *
     */
    public function testUpdateConsignPreference()
    {
    }
}
